### ISSUE TITLE
Inquiry about the availability of pre-trained weights for LibreFace

### ISSUE THREAD

**Issue by weiwuxian1998** [ihp-lab/LibreFace#1]
Hi, I found your work to be very interesting and it has potential implications for my current project.

In particular, I am interested in utilizing your model for my own purposes. However, I noticed that the pre-trained weights for your model were not provided in the github project. Therefore, I want to inquire if you have any plans to release the pre-trained weights for public use? If so, could you please provide me with more information on how to obtain them? Look forward your reply!

**Comment by KanaHayama** [comment]
I am not a developer of this repository, but I think those .pt files are the weight files.

**Comment by weiwuxian1998** [comment]
@KanaHayama Thanks  for your reply, I tested these .pt files and they are indeed the released weights files

**Comment by yanzichuan** [comment]
预训练权重怎么获得呢朋友
